// skills/scaffold-umbrella-with-turbo-and-pnpm/assets/templates/frontend/svelte-ui/src/ExampleCalculator.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Calculator } from '@umbrella/example-calculator';
  import { createCalculatorClient } from '@umbrella/calculator-client';

  const calculator = new Calculator();
  const client = createCalculatorClient({ baseUrl: '/api' });

  let left = $state(0);
  let right = $state(0);
  let result = $state<number | null>(null);
  let error = $state<string | null>(null);
  let status = $state<'idle' | 'loading' | 'saved' | 'offline'>('loading');

  onMount(async () => {
    const stored = await client.loadStoredValue();
    if (stored !== null) {
      result = stored;
    }
    status = 'idle';
  });

  function run(operation: 'add' | 'subtract' | 'multiply' | 'divide') {
    error = null;
    try {
      const next = calculator[operation](Number(left), Number(right));
      result = next;
      void client.persistValue(next).then((ok) => {
        status = ok ? 'saved' : 'offline';
      });
    } catch (err) {
      result = null;
      error = err instanceof Error ? err.message : 'Calculation failed';
    }
  }
</script>

<form onsubmit={(event) => event.preventDefault()} aria-busy={status === 'loading'}>
  <label>
    Left
    <input type="number" name="left" bind:value={left} />
  </label>
  <label>
    Right
    <input type="number" name="right" bind:value={right} />
  </label>
  <div>
    <button type="button" onclick={() => run('add')}>Add</button>
    <button type="button" onclick={() => run('subtract')}>Subtract</button>
    <button type="button" onclick={() => run('multiply')}>Multiply</button>
    <button type="button" onclick={() => run('divide')}>Divide</button>
  </div>
  {#if status === 'loading'}
    <p>Loading saved value…</p>
  {/if}
  {#if status === 'saved'}
    <p role="status">Saved</p>
  {/if}
  {#if status === 'offline'}
    <p role="status">Result shown locally; persist is offline</p>
  {/if}
  {#if result !== null}
    <p>Result: {result}</p>
  {/if}
  {#if error}
    <p role="alert">{error}</p>
  {/if}
</form>

// skills/scaffold-umbrella-with-turbo-and-pnpm/assets/templates/frontend/vue-ui/src/ExampleCalculator.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { Calculator } from '@umbrella/example-calculator';
import { createCalculatorClient } from '@umbrella/calculator-client';

const calculator = new Calculator();
const client = createCalculatorClient({ baseUrl: '/api' });

const left = ref(0);
const right = ref(0);
const result = ref<number | null>(null);
const error = ref<string | null>(null);
const status = ref<'idle' | 'loading' | 'saved' | 'offline'>('loading');

onMounted(async () => {
  const stored = await client.loadStoredValue();
  if (stored !== null) {
    result.value = stored;
  }
  status.value = 'idle';
});

function run(operation: 'add' | 'subtract' | 'multiply' | 'divide') {
  error.value = null;
  try {
    const next = calculator[operation](Number(left.value), Number(right.value));
    result.value = next;
    void client.persistValue(next).then((ok) => {
      status.value = ok ? 'saved' : 'offline';
    });
  } catch (err) {
    result.value = null;
    error.value = err instanceof Error ? err.message : 'Calculation failed';
  }
}
</script>

<template>
  <form @submit.prevent :aria-busy="status === 'loading'">
    <label>
      Left
      <input v-model.number="left" type="number" name="left" />
    </label>
    <label>
      Right
      <input v-model.number="right" type="number" name="right" />
    </label>
    <div>
      <button type="button" @click="run('add')">Add</button>
      <button type="button" @click="run('subtract')">Subtract</button>
      <button type="button" @click="run('multiply')">Multiply</button>
      <button type="button" @click="run('divide')">Divide</button>
    </div>
    <p v-if="status === 'loading'">Loading saved value…</p>
    <p v-if="status === 'saved'" role="status">Saved</p>
    <p v-if="status === 'offline'" role="status">Result shown locally; persist is offline</p>
    <p v-if="result !== null">Result: {{ result }}</p>
    <p v-if="error" role="alert">{{ error }}</p>
  </form>
</template>
