// skills/scaffold-umbrella-with-turbo-and-pnpm/assets/templates/frontend/vue-ui/src/ExampleCalculator.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { Calculator } from '@umbrella/example-calculator';
import { createCalculatorClient } from '@umbrella/calculator-client';

const calculator = new Calculator();
const client = createCalculatorClient({ baseUrl: '/api' });

const left = ref(0);
const right = ref(0);
const result = ref<number | null>(null);
const error = ref<string | null>(null);
const status = ref<'idle' | 'loading' | 'saved' | 'offline'>('loading');

onMounted(async () => {
  const stored = await client.loadStoredValue();
  if (stored !== null) {
    result.value = stored;
  }
  status.value = 'idle';
});

function run(operation: 'add' | 'subtract' | 'multiply' | 'divide') {
  error.value = null;
  try {
    const next = calculator[operation](Number(left.value), Number(right.value));
    result.value = next;
    void client.persistValue(next).then((ok) => {
      status.value = ok ? 'saved' : 'offline';
    });
  } catch (err) {
    result.value = null;
    error.value = err instanceof Error ? err.message : 'Calculation failed';
  }
}
</script>

<template>
  <form @submit.prevent :aria-busy="status === 'loading'">
    <label>
      Left
      <input v-model.number="left" type="number" name="left" />
    </label>
    <label>
      Right
      <input v-model.number="right" type="number" name="right" />
    </label>
    <div>
      <button type="button" @click="run('add')">Add</button>
      <button type="button" @click="run('subtract')">Subtract</button>
      <button type="button" @click="run('multiply')">Multiply</button>
      <button type="button" @click="run('divide')">Divide</button>
    </div>
    <p v-if="status === 'loading'">Loading saved value…</p>
    <p v-if="status === 'saved'" role="status">Saved</p>
    <p v-if="status === 'offline'" role="status">Result shown locally; persist is offline</p>
    <p v-if="result !== null">Result: {{ result }}</p>
    <p v-if="error" role="alert">{{ error }}</p>
  </form>
</template>

// skills/scaffold-umbrella-with-turbo-and-pnpm/assets/templates/frontend/angular-ui/src/example-calculator.component.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Calculator } from '@umbrella/example-calculator';
import { createCalculatorClient } from '@umbrella/calculator-client';

const client = createCalculatorClient({ baseUrl: '/api' });

@Component({
  selector: 'example-calculator',
  standalone: true,
  imports: [FormsModule],
  template: `
    <form (submit)="$event.preventDefault()" [attr.aria-busy]="status() === 'loading'">
      <label>
        Left
        <input type="number" name="left" [(ngModel)]="left" />
      </label>
      <label>
        Right
        <input type="number" name="right" [(ngModel)]="right" />
      </label>
      <div>
        <button type="button" (click)="run('add')">Add</button>
        <button type="button" (click)="run('subtract')">Subtract</button>
        <button type="button" (click)="run('multiply')">Multiply</button>
        <button type="button" (click)="run('divide')">Divide</button>
      </div>
      @if (status() === 'loading') {
        <p>Loading saved value…</p>
      }
      @if (status() === 'saved') {
        <p role="status">Saved</p>
      }
      @if (status() === 'offline') {
        <p role="status">Result shown locally; persist is offline</p>
      }
      @if (result() !== null) {
        <p>Result: {{ result() }}</p>
      }
      @if (error()) {
        <p role="alert">{{ error() }}</p>
      }
    </form>
  `,
})
export class ExampleCalculatorComponent {
  private readonly calculator = new Calculator();

  left = 0;
  right = 0;
  readonly result = signal<number | null>(null);
  readonly error = signal<string | null>(null);
  readonly status = signal<'idle' | 'loading' | 'saved' | 'offline'>('loading');

  constructor() {
    void this.hydrate();
  }

  private async hydrate(): Promise<void> {
    const stored = await client.loadStoredValue();
    if (stored !== null) {
      this.result.set(stored);
    }
    this.status.set('idle');
  }

  run(operation: 'add' | 'subtract' | 'multiply' | 'divide'): void {
    this.error.set(null);
    try {
      const next = this.calculator[operation](Number(this.left), Number(this.right));
      this.result.set(next);
      void client.persistValue(next).then((ok) => {
        this.status.set(ok ? 'saved' : 'offline');
      });
    } catch (err) {
      this.result.set(null);
      this.error.set(err instanceof Error ? err.message : 'Calculation failed');
    }
  }
}
